SELECT *
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC


SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC


SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'SICK'
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'AGED'
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME ASC, DATETIME DESC


SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1


SELECT MAX(DATETIME)
FROM ANUMAL_INS


SELECT MIN(DATETIME)
FROM ANIMAL_INS


SELECT COUNT(ANIMAL_ID)
FROM ANIMAL_INS


SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS


SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC


SELECT NAME, COUNT(NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME


SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME) ASC


-- WITH RECURSIVE 구분 (재귀/계층)
/* WITH RECURSIVE TABLE이름 AS
 * (SELECT - 반복되지 않는 부분
 * UNION ALL
 * SELECT ~
 * WHERE 정지 조건
 */
WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 
    FROM TIME
    WHERE HOUR < 23
)
SELECT HOUR, COUNT(DATETIME) AS COUNT 
FROM TIME
LEFT OUTER JOIN ANIMAL_OUTS
ON HOUR(DATETIME) = HOUR
GROUP BY HOUR
ORDER BY HOUR


SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL


SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_TYPE, IFNULL(NAME, 'No name') AS NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID


SELECT O.ANIMAL_ID AS ANIMAL_ID, O.NAME AS NAME
FROM ANIMAL_OUTS AS O LEFT OUTER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.DATETIME < I.DATETIME
ORDER BY I.DATETIME ASC


SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME ASC
LIMIT 3


SELECT O.ANIMAL_ID AS ANIMAL_ID, O.ANIMAL_TYPE AS ANIMAL_TYPE, O.NAME AS NAME
FROM ANIMAL_OUTS AS O 
LEFT OUTER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE SEX_UPON_OUTCOME IN ('Spayed Female', 'Neutered Male')
AND SEX_UPON_INTAKE IN ('Intact Female', 'Intact Male')
ORDER BY ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE NAME IN ('Lucy', 'Ella', 'Pickle', 'Rogan', 'Sabrina','Mitty')


SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE NAME LIKE '%EL%'
AND ANIMAL_TYPE = 'DOG'
ORDER BY NAME ASC


SELECT ANIMAL_ID, NAME, CASE WHEN SEX_UPON_INTAKE LIKE 'NEUTERED%' THEN 'O'
                             WHEN SEX_UPON_INTAKE LIKE 'SPAYED%' THEN 'O'
                        ELSE 'X'
                        END '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC


SELECT O.ANIMAL_ID AS ANIMAL_ID, O.NAME AS NAME
FROM ANIMAL_OUTS AS O LEFT OUTER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
ORDER BY O.DATETIME - I.DATETIME DESC
LIMIT 2


SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC

